---
title: "Lecture 1.3"
data: 2024-01-08
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Tidy data

### not tidy

```{r}
# untidy data ----
temp_data_wide <- tribble(
  ~date, ~station1, ~station2,  ~station3,
  "2023-10-01", 30.1, 29.8,  31.2,
  "2023-11-01", 28.6, 29.1,  33.4,
  "2023-12-01", 29.9, 28.5,  32.3
)
```

### tidy

```{r}
# make tidy ----
temp_data_long <- temp_data_wide |> 
  pivot_longer(cols = starts_with("station"), # transform all columns that start with "station" into rows
               names_to = "station_id", 
               values_to = "temp_c")

# what makes data tidy:
# each observation forms a single row; 
# column names are descriptive
```

### plot1

```{r}
# mapping color globally
ggplot(data = na.omit(penguins),
       mapping = aes(x =  bill_length_mm,
                     y = bill_depth_mm,
                     color = species)) +
  geom_point() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  theme_minimal()

# mapping color locally
ggplot(data = na.omit(penguins),
       mapping = aes(x =  bill_length_mm,
                     y = bill_depth_mm)) +
  geom_point(aes(color = species,
                 size = species)) +
  geom_smooth(method = "lm")
  theme_minimal()
  
ggplot(penguins, aes(x = body_mass_g,
                     y = flipper_length_mm,
                     color = body_mass_g)) +
  geom_point() +
  scale_color_gradient(low = "#132B43", high = "#F7DD4C")
```


### Plot 2

```{r}
ggplot(penguins, aes(x = species)) +
  geom_bar()
```

### Overriding geom_bar stat

```{r}
penguins_summary <- penguins %>% 
  count(species)

ggplot(penguins_summary, 
       aes(x = species, y = n)) +
  geom_bar(stat = "identity") # identity = the height of the bar means the value in the dataset (e.g. here value n)
```

### Overriding default stat mapping

```{r}
ggplot(penguins, aes(x = species, y = after_stat(prop), 
                     group = 1)) + # prop = proportion
  geom_bar()
```

### position adjustments

```{r}
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = position_dodge2(preserve = "single")) # default position = stack
```


### Coordinate systems + themes
```{r}
ggplot(penguins, aes(x = species)) +
         geom_bar() +
         coord_flip() +
  theme_classic() +
  theme(
    axis.title = element_text(size = 17, color = "purple")
  )
```

```{r}
source(here::here("week3", "KEYS.R"))
```

